- lua/configs/dashboard.lua
Thank you for publishing a very useful and cool project.
I found something wrong about the "New File" icon on the dashboard.
As you can see in the video below, the behavior of the cursor on the "New File" is different from the other items.
The cursor moves to the second letter "e" instead of the first letter "N".
https://user-images.githubusercontent.com/38152917/152708229-7160650c-3835-4bd1-b3c1-a80532d899fc.mp4
So I replaced it with the correct "plus" icon of Nerd Font.
It now works correctly, as shown in the following video.
https://user-images.githubusercontent.com/38152917/152708234-2b3d2180-1082-414c-ae6b-56a82ee5d543.mp4
> Fix the icon of "New File" on the dashboard

- lua/core/defaults.lua
- lua/core/plugins.lua
Closes: #39
I think it is safe to remove the `after = "bufferline"` from `lualine`: I could not spot any mention of bufferline in the lualine config.
The history of plugins.lua unfortunately gave no hint why this ordering was considered encessary.
> Add option to disable bufferline

- README.md
- lua/configs/treesitter.lua
- lua/core/defaults.lua
This PR allows overriding the treesitter options to give the user more control.
The main purpose for this was to be able to define the parsers that should be installed in the configuration file without having to install them via command. This allows a faster and easier setup of Neovim on new/other machines.
> Allow overriding treesitter options

- init.lua
- lua/core/defaults.lua
Add an optional polish function into the user settings that is run right
before returning control to neovim. This is a nice place to override
choices made be AstroVim :-)
> Add an optional polish function

- lua/configs/lsp/lsp-installer.lua
... instead of relying on the LSP being found in PATH.
> Make LSP Installer provide pathes to installed binaires

- lua/configs/lsp/lsp-installer.lua
- lua/core/defaults.lua
This is needed for special plugins like `rust.tools.nvim` that extend
the typical LSP support significantly.
This can also be used to override lsp server settings from the user settings, but we should probably have a nicer thing for that... Users have full control via this override of all data passed into the LSP server registration with this hook.
> Lsp-installer: Allow to override how language servers are registered

- lua/configs/telescope.lua
Not sure this patch makes sense for AstroVim...
The `smart` path_display is unfortunately pretty dumb.
Convention in rust is to have a directory layout like this `[lib_name]/src/lib.rs`. The `smart` policy in Telescope displays those as `.../src/lib.rs` -- for all the libraries and independent of wheether the full path would fit or not! That makes the whole search pretty pointless for me.
`truncate` will just cut off from the start of the file, but at least it will not truncate when there is enough space to display the entire name without truncating anything!
> Telescope: Show more of the file path in search

- lua/core/mappings.lua
Ex-mode is not widely used and it is hard to get out off again,
so disable it by default.
> Disable Ex mode

- lua/configs/lualine.lua
Code is taken from NVChad under GPL-3.0.
The LSP progress information is *extremely* nice to have when working with a big C++ project, where clangd can take >10min to chew through the entire project before it is ready to actually work!
> Make lualine display status messages

- lua/core/plugins.lua
This project defines a mapping for `NvimTreeFocus`. This will fail on first use because  nvim-tree is not loaded. 
This change ensures that nvim-tree is loaded if a user calls `NvimTreeFocus` before they have called `NvimTreeToggle`
> Allow loading nvim-tree when using focus command

- lua/configs/bufferline.lua
When the Symbol Outline is part of the Bufferline it causes weird behavior when opening new files and stuff from the file browser when the outline is open and also makes an empty tab for the symbols. Seems to make more sense to ignore it.
> Remove Outline from Bufferline

- lua/configs/lsp/server-settings/yamlls.lua
This works with the schemastore plugin: I get errors when using invalid keywords in .github action setup yaml files.
> Add configuration for yamlls (using schemastore plugin)

- init.lua
- lua/core/defaults.lua
- lua/core/plugins.lua
- lua/core/utils.lua
- lua/user/settings.lua
My config directory is read-only, so Packer fails in AstroVim as it can not write its `packer_compiled.lua` file.
So here is a PR to make that file location configurable. The default is of course the location you currently use:-)
> Packer move

- lua/configs/lsp/server-settings/yamlls.lua
This file is not doing anything since `schemastore` is not properly formatted for the yamlls. yamlls in nvim lspconfig has built in schema store compatibility pulling from https://www.schemastore.org/api/json/catalog.json
This makes it appear that it is working with this file, but in actuality it's doing nothing.
> Removed yamlls server settings

- lua/onedark/others.lua
Leave the forground alone, so syntac highlighting continues to work,
but make the background lighter than the one in the surrounding area.
> Better highlight for the Telescope match in the preview

- lua/core/plugins.lua
It just adds a couple of new commands that you do not have to use, so it
does not hurt to enable the plugin unconditionally, even when no
bufferline is installed.
Most users should not notice this as bufferline is enabled by default.
> Enable bbye plugins

- lua/configs/telescope.lua
This was discussed briefly in the Discord discussions that maybe we should move the prompt to the top and reverse the results picker. I went ahead and did this locally and figured I would suggest it here. Screenshot below:
> Change telescope layout to seem more natural

- README.md
- lua/core/defaults.lua
- lua/core/plugins.lua
This change allows users to manipulate the lua table passed to packer to
load plugins, allowing to override every aspect of the configuration.
Note that this is very low level and not suited to change plugin
configuration since there the configuration suggested by AstroVim is
lost at this point.
Fixes #113, Fixes #114
See the README.md change for an example on how to use this.
> Allow to polish plugins before loading

- lua/configs/cmp.lua
This commit does a few things to improve the usability of `cmp`
1. It does not auto select the first entry in the list. It must be specifically selected with ctrl-j/k or arrow keys. At the end of lines if I just want to type a new line and press enter and there is a possible selection it inserts it instead of a new line even though I did not select it.
2. Disabled the tab/s-tab for moving up and down in the list of completions. This is already enabled with ctrl-j/k and arrow keys and while the completion menu is open you can no longer jump between locations in a snippet without first pressing ctrl-e to close the menu.
Both of these issues cause behavior to change based on the menu being open and closed when interacting with the snippets and requires the user to think more before pressing …
> Make cmp more predictable and usable

- README.md
- lua/configs/autopairs.lua
- lua/configs/bufferline.lua
- lua/configs/cmp.lua
- lua/configs/comment.lua
- lua/configs/gitsigns.lua
- lua/configs/icons.lua
- lua/configs/indent-line.lua
- lua/configs/lsp/lspsaga.lua
- lua/configs/lualine.lua
- lua/configs/neoscroll.lua
- lua/configs/nvim-tree.lua
- lua/configs/symbols-outline.lua
- lua/configs/telescope.lua
- lua/configs/toggleterm.lua
- lua/configs/treesitter.lua
- lua/configs/which-key.lua
- lua/core/utils.lua
This sets up a system that extends the `overrides` table in the user settings where the user can arbitrarily overwrite and extend any default plugin configuration files. 
Fixes #115, Fixes #112, Fixes #111
> Add arbitrary user configuration of default plugins

- lua/configs/lualine.lua
- lua/core/status.lua
Extract the status functions from configs/lualine.lua into
core.status.lua.
This allows to reuse them in other places or with reconfigured lualines.
> Lualine: Extract status functions

- lua/user/settings.lua
The `polish` function commits were a breaking change and makes the user config outside of the polish function not work. This fixes the default config.
Fixes #96
> Fix incorrect user config

- README.md
- lua/core/plugins.lua
- lua/core/utils.lua
This extends the user overrides a bit more. While maintaining the original API and no breaking changes
1. The user can define a `.lua` file in the `user` directory instead of in the `overrides` table and it will be treated as if it were in the overrides table where the filename is the key
2. instead of a table, the user can define a function that returns a table with a single parameter (i.e. `function(table)`) where the parameter passed in is the table that would be set and the function must return a table that will in turn  be set.
Example, if the user wants to override a `cmp` binding they can either put it in the `overrides` table in `settings.lua` using a function:
```lua
overrides = {
cmp = function(table)
local status_ok, cmp = pcall(require, "cmp")
if not status_ok then
return …
```
> More extension for user settings

- lua/core/mappings.lua
Fixed typo in mappings.lua.
fixes #132
> Fixed typo in mappings.lua

- lua/core/plugins.lua
This is a pretty simple change. It adds some ugliness to the `plugins.lua` table but is something the user will never have to really look at. Currently when overriding the plugins with a function if I want to disable lazy loading of a single plugin I have to do this:
```lua
function(plugins)
local result = {}
for _, plugin in pairs(plugins) do
if plugin[1] == "akinsho/nvim-toggleterm.lua" then
plugin["cmd"] = nil
end
table.insert(result, plugin)
end
return result
end
```
This would allow the user to do something much simpler:
```lua
function(plugins)
plugins["akinsho/nvim-toggleterm.lua"]["cmd"] = nil
return plugins
end
```
This contains no breaking changes as these keys are not used internally at all and just provide a nice interface for the user if they want to override specific plugin …
> Add keys to plugin table

- lua/core/plugins.lua
I think nvim-tree has stabilized a bit. We can unpin the commit.
Fixes #121
> Unpin nvim-tree commit

- lua/core/autocmds.lua
This is already taken care of with https://github.com/kabinspace/AstroVim/blob/db5e1523d27c3315e2e3632d6d0a14c8f6e704e4/lua/configs/dashboard.lua#L9
Fixes #140
> Remove dashboard statusline autocmd

- lua/core/utils.lua
Running `:AstroUpdate` shows "Update Failed" on the first run even when it does not actually fail. This is due to `git pull` printing output to stderr even on success. We should be checking for successful runs instead. This fixes that as well as fixes the error output.
> Fix AstroUpdate 'failing' on the first run

- lua/configs/colorizer.lua
- lua/configs/lsp/handlers.lua
- lua/configs/lsp/lsp-installer.lua
- lua/core/defaults.lua
- lua/core/utils.lua
This PR makes the user configuration more robust. Adds a few features:
- custom `server-settings` can now be put in the overrides table instead of just in files like this:
```lua
overrides = {
["server-settings"] = {
yamlls = {
settings = {
yaml = {
schemas = {
["http://json.schemastore.org/github-workflow"] = ".github/workflows/*.{yml,yaml}",
["http://json.schemastore.org/github-action"] = ".github/action.{yml,yaml}",
["http://json.schemastore.org/ansible-stable-2.9"] = "roles/tasks/*.{yml,yaml}",
},
},
},
},
},
}
```
- stuff like the `lsp_installer` options for `on_attach_override` and `server_registration_override` can now be put into separate files instead of just in the `overrides` table under `user/lsp_installer/on_attach_override.lua` and …
> Make user config function more robust

- lua/configs/telescope.lua
- lua/core/plugins.lua
The extension is the default anyway, so I just removed that...
This makes it possible to just disable the fzf plugin without killing the telescope plugin as well -- e.g. because you can not actually build the fzf binary this needs:-)
> Make telescope-fzf more stand-alone

- lua/default_theme/colors.lua
- lua/default_theme/init.lua
- lua/user_example/init.lua
This allows the user to override colors and highlight groups inside of `init.lua`
example:
```lua
local config = {
default_theme = {
colors = {
bg = "#1e222a",
},
highlights = {
TSField = { fg = "#C9CBFF", style = "italic" },
},
}
}
return config
```
Example using the color table:
```lua
return {
default_theme = {
colors = {
bg = "#1e222a",
lavender = "#C9CBFF", -- add a new color
},
highlights = function(highlights)
local C = require "default_theme.colors"
highlights.TSField = { fg = C.lavender, style = "italic" }
return highlights
end,
},
}
```
> Allow user to override any entry in the default_theme

- lua/core/plugins.lua
I accidentally added an entry that is not real packer syntax. This fixes that.
> Fix packer syntax wants to after

- README.md
The default theme for AstroVim does require true color support. Added this to the requirements as well as a note regarding Mac OS X users.
Fixes #101
> True color notice

- lua/core/mappings.lua
This adds better buffer control if bufferline is enabled since reordering the bufferline tabs messes up the `bnext`/`bprevious` commands. Also adds `{` and `}` for reordering tabs
> Add better mappings when bufferline is enabled

- lua/core/mappings.lua
`^w` causes conflicts with the window bindings like `^ws` and `^wT` 
fixes #191
> Rebind save to ^s

- lua/core/mappings.lua
Renaming is taken care of with the `<leader>lr` binding and `rn` conflicts with replacing a character with `n`
> remove conflicting rn binding

- lua/core/mappings.lua
- lua/core/plugins.lua
This makes the default resizing and split movement bindings more intuitive to the user.
> Move to smart-splits for split movement and resizing

- lua/configs/treesitter.lua
the Treesitter indent module is experimental (as said in their docs) and it was apparent specifically with Python. Disable it by default.
Fixes #199
> disable treesitter indentation module

- init.lua
Compiled packer configs run after the polish function, we should change this ordering.
Resolves #228
> Move polish function to truly running last

- lua/configs/cmp.lua
- lua/core/mappings.lua
Adds back tab completion to CMP and fixed `p` when navigating snippets
Fixes #230
> Add tab selection for cmp

- lua/configs/neo-tree.lua
- lua/default_theme/colors.lua
- lua/default_theme/others.lua
- Change highlight groups
- Disable diagnostics
- Disable signcolumn
- Show git ignored and dot files
> Disable diagnostics on neotree

- lua/configs/neo-tree.lua
Before this commit it becomes actually impossible to hide the dotfiles in the tree so the toggle visibility function becomes useless 😂
> Fix hiding dotfiles but maintaining that they show by default

- lua/configs/neo-tree.lua
This makes hidden files (dotfiles) actually hidden by default just like every other file manager as well as the default telescope search.
> fix hidden files in neo-tree

- lua/core/plugins.lua
Makes `cmp` load on InsertEnter instead of BufWinEnter. We need to make sure it doesn't bring back the problems that #236 solved. (We need to make sure rust LSP starts when selecting from neo-tree still.
> improve cmp lazy loading

- init.lua
- lua/core/defaults.lua
- lua/core/plugins.lua
- lua/core/ui.lua
- lua/user_example/init.lua
Now that we are using `neo-tree` we need to use `nui.nvim`. With that being the case it doesn't make sense to include 2 plugins that improve the neovim user interface. This replaces dressing nvim stuff with just nui. After doing some testing I have also found that this geatly increases load time because we can easily still lazy load both `nui` and `telescope`. Also `nui` is faster than `dressing`.
This does include wrapping up our own vim ui functions instead of using plugins, but this allows us to have users toggle either one or both of the features off depending on what plugins they like using while also letting us lazy load nicely.
> Move from dressing to NUI vim ui

- .luacheckrc
- init.lua
- lua/core/autocmds.lua
- lua/core/mappings.lua
- lua/core/utils.lua
This allows the use of packer global table to control mappings/autocommands instead of user defined variables. Much more robust and decreases start up time
> Generalize plugin enable/disable API

- lua/configs/filetype.lua
- lua/configs/neo-tree.lua
I just discovered that the diagnostic signs are already defined here:
https://github.com/kabinspace/AstroVim/blob/187c756f7f1c5168e3ba88a2ce55f71837378ab6/lua/configs/lsp/handlers.lua#L4-L9
So I removed those from the Neo-tree config as we don't really need to redefine them again.
Also corrected a small typo in the filetype config. 🙂
> Remove duplicated diagnostic sign definition (LSP)

- lua/configs/which-key-register.lua
- lua/core/mappings.lua
This sets up which-key assigning mappings if it is available and `mappings.lua` assigning mappings if it is not. This does require core maintenance to duplicate code for leader and non-leader mappings but on the user side if `which-key` is used the user can simply override the which-key register table without also having to unmap or delete mappings as well.
> Move binding setting to which-key for easier user override in config

- init.lua
- lua/core/utils.lua
This adds `$XDG_CONFIG_HOME/astrovim` to the runtime path so the user folder can now go in `$XDG_CONFIG_HOME/astrovim/lua/user/`. Note the `$XDG_CONFIG_HOME/astrovim` folder location takes precedence over `$XDG_CONFIG_HOME/nvim`.
Resolves #276
> Add ability to put user config in ~/.config/astrovim/lua/user

- lua/configs/cmp.lua
`cmp` recently had a couple deprecations and breaking changes:
https://github.com/hrsh7th/nvim-cmp/issues/231#issuecomment-1098149666
https://github.com/hrsh7th/nvim-cmp/issues/231#issuecomment-1098175017
> Fix breaking cmp changes

- lua/configs/cmp.lua
- lua/core/defaults.lua
- lua/core/plugins.lua
- lua/core/utils.lua
- lua/user_example/init.lua
Takes ideas from #291 to move priorities to be more modular while giving the user a means of easily changing the defaults that are chosen through the user config table.
> Improve modularity of cmp sources while maintaining priority

- lua/core/utils.lua
This adds the ability for the user to access the user_terminals table from outside of the `utils.lua` module as well as extend the features when creating a togglable terminal.
Fixes #299 and Fixes #296
> Extend ToggleTerminal function and access

- lua/core/utils.lua
enhance #300 by providing (optional) terminal number
e.g. key stroke 4tp with open python in terminal  number 4
> Add optional terminal numbers to toggle term

- lua/core/plugins.lua
`nvim-lspconfig` is about to do a bunch of breaking changes with adding v0.7 support. We will need to keep this commit tagged until those changes get merged in and we can update the config to fix the breaking part.
> Fix lsp config to v0.1.3

- lua/configs/lsp/handlers.lua
- lua/core/autocmds.lua
This gives command descriptions that look nice when searching commands with something like `:Telescope commands`
> Add descriptions to user commands

- lua/configs/lualine.lua
- lua/core/status.lua
Small detail in lualine and the status.
I am using windows terminal and it happens to me with VictorMono, FiraCode CaskaydiaCode
> Detail lualine and status

- lua/configs/dashboard.lua
dashboard shows "Space b m" when in the mapping it is "Space f m"
> Detail visual in dashboard

- lua/core/ui.lua
Telescope recently had a breaking change resulting in a stackoverflow in our code. See more details here: https://github.com/stevearc/dressing.nvim/issues/36
Fixes: #339
> Fix telescope stack overflow

- lua/configs/which-key-register.lua
- lua/core/mappings.lua
This adds a few more bindings to our which-key while also adding a more general approach to user configuration with which-key. I did leave the original `which-key.register_n_leader` table as an option for no breaking changes. But I added `which-key.register_mappings` which can support registering all modes and prefixes. Something like this:
```lua
return {
["which-key"] = {
register_mappings = {
n = {
["<leader>"] = {
-- normal mode leader prefix mappings,
},
g = {
-- normal mode g prefix mappings
}
},
v = {
["<leader>"] = {
-- visual mode leader prefix mappings...
}
}
}
}
}
```
> Generalize which-key registration

- lua/configs/lsp/handlers.lua
- lua/configs/lsp/init.lua
If a plugin sets up LSP specific capabilities and on_attach functions then we should respect that when we call our own language server setups.
> Add LSP Extension Plugin Compatibility

- lua/core/plugins.lua
We can unpin `lspconfig` I did some testing with the v0.7 branch and we are fully compatible and won't have any breaking changes when https://github.com/neovim/nvim-lspconfig/pull/1838 get's merged
> Unpin lspconfig

- lua/configs/aerial.lua
- lua/configs/lsp/handlers.lua
- lua/configs/symbols-outline.lua
- lua/configs/which-key-register.lua
- lua/core/mappings.lua
- lua/core/plugins.lua
- lua/default_theme/others.lua
This is a work in progress PR for moving to Aerial from Symbols Outline for more general support with Treesitter.
Resolves #377
> Move from Symbols Outline to Aerial

- lua/configs/lsp/handlers.lua
- lua/user_example/init.lua
I did  some more investigation into the resolved_capabilities deprecation as shown  by #421 and the new approach is almost supported by neovim 0.7. It appears the  formatter does check the `resolved_capabilities` so we need one of the deprecated approaches still  but we can check for neovim version. I think it's a good idea to move to this approach  now.
> Removed deprecated LSP resolved_capabilities

- lua/core/mappings.lua
- lua/core/options.lua
- lua/core/utils.lua
- lua/user_example/init.lua
This streamlines vim options setting into a nice API. Also since we are setting user options first then we can use it to guide the Alpha welcome screen text.
Also this adds checking for if a colorscheme is installed. So the user no longer has to worry about checking if their plugin is loaded themselves.
> Streamline options setting and automatically check for colorscheme

- lua/core/mappings.lua
This adds basic split mappings if smart split is removed.
> add fallback mappings for split movement and resize

- lua/core/autocmds.lua
These auto commands are causing more harm than good. I think for now it's a good idea to remove them.
> Remove cursorline autocommands

- lua/core/mappings.lua
Our current bindings are really bad conflicts. This puts them in logical mappings that don't conflict with the indentation command
> Bufferline reorder buffer mappings

- lua/configs/lsp/handlers.lua
- lua/user_example/init.lua
It appears not every language server is setting the `server_capabilities` quite yet. So we should revert this for more consistency
> Revert back to just using resolved_capabilities

- lua/core/autocmds.lua
- lua/core/plugins.lua
This takes a first stab at lazy loading alpha if neovim is opened with a file.
This lazy loading is not quite as sophisticated as the alpha starting conditions.
Resolves #471
> Add lazy loading to alpha

- lua/configs/indent-line.lua
At the moment installing AstroNvim gives following error:
This PR should fix this.
> fixed require for indent-line.lua

- lua/configs/lsp/handlers.lua
- lua/core/mappings.lua
When we moved the lsp bindings to only get bound when an lsp is attached we accidentally moved the `nvim-lsp-installer` bindings which should always be available.
> Make lsp installer mappings always available

- lua/configs/which-key.lua
When Telescope window is opened, in normal mode, if we press `<leader>` key (SPC by default). It will show an error like below:
This fix is disable which-key popup when Telescope is still opened.
> Don't show which-key popup when Telescope window is opened

- lua/configs/which-key.lua
Thanks @thieung for catching this issue and contributing the initial fix for which-key breaking telescope's normal mode. This adds a small extension to allow the user to override this function if they have different needs or conflicts with other plugins as well.
Extension of #491
> Telescope whichkey fix

- lua/configs/autopairs.lua
- lua/configs/better_escape.lua
- lua/configs/indent-o-matic.lua
- lua/configs/lsp/init.lua
- lua/configs/luasnip.lua
- lua/configs/notify.lua
- lua/configs/null-ls.lua
- lua/core/plugins.lua
- lua/core/utils.lua
- lua/default_theme/utils.lua
- lua/user_example/init.lua
Right now we have a very specific set up for `null-ls`. This makes it treated like every other plugin.
> BREAKING: Treat null-ls like every other plugin

- lua/configs/lsp/handlers.lua
[nvim-lspconfig](https://github.com/neovim/nvim-lspconfig/wiki/Autocompletion#nvim-cmp) mentioned that we don't need to use omnifunc since  we are using `nvim-cmp`
> If you are using nvim-cmp do not use neovim's built-in omnifunc as it cannot support the additional completion items returned from servers due to the capabilities enabled by nvim-cmp.
> chore: disable omnifunc

- lua/configs/cmp.lua
- lua/core/utils.lua
This allows the user to call the other `cmp.setup.X` calls with a simple table in the `user/init.lua` file. An example of an in depth setup for this is:
```lua
local buffer_source = {
name = "buffer",
option = {
get_bufnrs = function()
local bufs = {}
for _, win in ipairs(vim.api.nvim_list_wins()) do
bufs[vim.api.nvim_win_get_buf(win)] = true
end
return vim.tbl_keys(bufs)
end,
},
}
return {
plugins = {
init = {
["hrsh7th/cmp-buffer"] = {
config = function()
astronvim.add_user_cmp_source(buffer_source)
end,
},
},
},
cmp = {
source_priority = {
luasnip = 1000,
nvim_lsp = 750,
nvim_lsp_signature_help = 700,
pandoc_references = 600,
buffer = 500,
path = 250,
emoji = 200,
dictionary = 150,
},
setup = function()
local cmp = require "cmp"
local user_source = astronvim.get_user_source
local …
```
> feat(cmp): add user config for extension cmp setup calls

- .gitignore
I use symlinks a lot to manage my configuration files and apparently, a trailing slash does not match a symlink to a directory, I hope it is ok to make this little change
And thank you for this configuration, absolutely loving it so far!
> chore(gitignore): drop trailing slash from lua/user path

- lua/core/status.lua
I notice one problem that if you open a random file, the lsp_clients_name will display properly but if you open another file on another directory, lsp_clients_name won't exist on that file.
> fix(status): remove lsp_client_name bug in feline

- lua/default_theme/plugins/bufferline.lua
Makes the currently selected buffer noticeable in the tab line. Useful when there are several visible buffers with splits.
> chore(bufferline): make selected buffer noticeable in bufferline

- lua/configs/lsp/handlers.lua
- lua/configs/lsp/init.lua
This further improves the user experience for setting up LSP  specific plugins. With this new helper function the user can do the following:
```lua
return {
lsp = {
skip_setup = { "tsserver" },
},
plugins = {
init = {
{
"jose-elias-alvarez/typescript.nvim",
after = "nvim-lsp-installer",
config = function()
require("typescript").setup {
server = astronvim.lsp.server_settings("tsserver")
}
end,
},
},
["nvim-lsp-installer"] = {
ensure_installed = { "tsserver" },
},
},
}
```
> feat(lsp): add helper function for getting server settings

- lua/core/autocmds.lua
- lua/core/utils.lua
This adds the command `:AstroVersion` which displays the latest tag and the current commit hash.
Resolves #584
> feat(core): add AstroVersion command to check version

- init.lua
- lua/configs/Comment.lua
- lua/configs/lsp/handlers.lua
- lua/configs/lsp/server-settings/html.lua
- lua/configs/lsp/server-settings/jsonls.lua
- lua/configs/lsp/server-settings/sumneko_lua.lua
- lua/configs/lsp/server-settings/tsserver.lua
- lua/configs/telescope.lua
- lua/configs/treesitter.lua
- lua/configs/which-key.lua
- lua/core/ui.lua
- lua/core/utils.lua
This allows additions to the `on_attach` function for specific language servers in the `lsp.server-settings` table. This was completely incorrectly handled and honestly could be considered just a flat out bug until now. For example, disabling formatting for a single language server can now look like this:
```lua
return {
lsp = {
["server-settings"] = {
html = {
on_attach = function(client, bufnr)
client.resolved_capabilities.document_formatting = false
end
}
}
}
}
```
Also makes it easier to disable our custom `on_attach` for specific languages, like if a user wants to use `tsserver` formatting they can just do this:
```lua
return {
lsp = {
["server-settings"] = {
tsserver = {
on_attach = function() end
}
}
}
}
```
> feat(lsp): allow user defined per lsp on_attach additions

- lua/core/options.lua
Some colorschemes which have multiple style options like:
- [marko-cerovac/material.nvim](https://github.com/marko-cerovac/material.nvim.git)
- [folke/tokyonight.nvim](https://github.com/folke/tokyonight.nvim)
Require their options to be set before setting up or enabling the colorscheme
---
So when I add the colorscheme plugin, and set it up like the following:
```lua
-- Set colorscheme
| colorscheme = "tokyonight",
-- set vim options here (vim.<first_key>.<second_key> =  value)
options = {
...
g = {
|     tokyonight_style = "night",
},
},
...
-- Configure plugins
plugins = {
-- Add plugins, the packer syntax without the "use"
init = {
|     { "folke/tokyonight.nvim" },
...
},
...
},
```
Each time I open nvim the default style option is loaded, and I need to run `:colorscheme tokyonight` …
> fix(core): Set colorscheme after opts

- .luacheckrc
- init.lua
- lua/configs/lsp/server-settings/sumneko_lua.lua
- lua/core/utils/git.lua
- lua/core/utils/init.lua
- lua/core/utils/updater.lua
- lua/user_example/init.lua
This moves the default packer compiled location the the data folder since it's not a config file. This also enables the ability for AstroNvim to easily be loaded in a non-git manner. Say with a package manager and disables the Updater.
Package managers need to set a global variable in Neovim when setting up the `runtimepath` that adds the new installation location. The variable is as follows:
```lua
_G.astronvim_installation = {
home = "<installation_runetime_path>",
version = "<installed_version_string>",
is_stable = true, -- boolean value of whether or not it's stable
}
```
Here is an example `astronvim.vim` that would be placed in `/usr/share/nvim/runtime/plugin/astronvim.vim` to autoload a nightly installation of `AstroNvim` installed to `/usr/share/astronvim`:
```vim
lua …
```
> feat: enable external package manager installations of astronvim

- .github/README.md
I spotted that in the latest release
`xclip` is for X11, `wl-clipboard` is for Wayland, and there actually are others:
```
clipboard-tool
The presence of a working clipboard tool implicitly enables the '+' and '*'
registers. Nvim looks for these clipboard tools, in order of priority:
- g:clipboard
- pbcopy, pbpaste (macOS)
- wl-copy, wl-paste (if $WAYLAND_DISPLAY is set)
- xclip (if $DISPLAY is set)
- xsel (if $DISPLAY is set)
- lemonade (for SSH) https://github.com/pocke/lemonade
- doitclient (for SSH) http://www.chiark.greenend.org.uk/~sgtatham/doit/
- win32yank (Windows)
- termux (via termux-clipboard-set, termux-clipboard-set)
- tmux (if $TMUX is set)
```
https://neovim.io/doc/user/provider.html#clipboard-tool
Windows does not seem to come with a pre-installed one either.
And as …
> docs: point to full list of supported clipboard tools

- .stylua.toml
The option has changed since https://github.com/JohnnyMorganz/StyLua/releases/tag/v0.12.0.
> ### Deprecated
> - Option `no_call_parentheses` has been deprecated. Use `call_parentheses = "None"` instead.
> chore(stylua): `no_call_parentheses` -> `call_parentheses`

- lua/configs/autopairs.lua
- lua/configs/cmp.lua
- lua/configs/which-key-register.lua
- lua/core/mappings.lua
- lua/core/options.lua
- lua/core/utils/init.lua
- lua/core/utils/ui.lua
- lua/user_example/init.lua
Building on discussion and tutoring at #764
I refactored original code set
Signed-off-by: Osamu Aoki <osamu@debian.org>
> Add User experience menu

- lua/configs/alpha.lua
- lua/configs/telescope.lua
As mentioned in issue [AstroNvim/issues/812](https://github.com/AstroNvim/AstroNvim/issues/812), the search icon in telescope is not working on iTerm2 terminal on mac with nerd font. To solve this problem, there is an other search icon that is really similar that works on Mac iTerm2 terminals.
This change is to fix this to allow all platform to have the search icon on telescope and the dashboard.
The exact change is the replacement of the `nf-oct-search` icon for the `nf-fa-search` icon.
These two screenshot were made on iTerm2 terminals with nvim version : 
```
NVIM v0.7.0
Build type: Release
LuaJIT 2.1.0-beta3
Compiled by brew@Monterey
```
Font is MesloLGS NF
> fix(telescope,alpha): search icon on iTerm2

- lua/core/plugins.lua
This is NvChad's fork of nvim-colorizer, which they use in their own project. It seems to be the most active out of the other forks. See https://github.com/norcalli/nvim-colorizer.lua/issues/75.
> chore(nvim-colorizer): switch to maintained fork

- lua/configs/window-picker.lua
- lua/core/autocmds.lua
- lua/core/plugins.lua
Neo-tree has added window picker keybindings which require a window-picker to be installed. This adds one and fully lazy loads it on it's module. If the user  never uses the keybinding then the plugin never loads.
This also adds an auto command that will auto close AstroNvim if a window is closed and only Aerial and Neo-tree are opened.
Resolves #733
> Neo-Tree Improvements

- lua/configs/lsp/handlers.lua
Hey when I was switching from VSCode to Astro I noticed that I couldn't refactor code when being in visual mode. I used that feautre very often in VSC when was working with Rust code
> Add missing range code action mapping

- lua/configs/Comment.lua
Minor correction to the Comment.nvim pre_hook function. As discussed in numToStr/Comment.nvim#201, `utils.ctype` attributes got renamed.
> Minor fix to Comment.nvim pre_hook

- lua/core/utils/lsp.lua
Fix not being able to globally disable format on save.
I had set a filter to always return false. So I ended up with this:
`type(formatting.filter) == "function"` == `true`.
`formatting.filter(client)` == `false`.
`true and false` == `false`.
So the branch after the `or` got evaluated, overriding my global "don't do that!".
> Fix formatting.filter

- lua/configs/colorizer.lua
After the last colorizer update, the following error started appearing when opening neovim:
`colorizer: Invalid type for filetypes "*"`
Fix making a modification to the `colorizer.lua` file
> fix(colorizer): fix Colorizer filetype error when opening neovim

- lua/core/utils/updater.lua
When checking for updates on the stable branch we shouldn't need to switch branches. Also this resets the head and makes it look like stable branches always have an update.
> fix(updater): fix update checker for stable channel

- lua/configs/mason-null-ls.lua
- lua/core/plugins.lua
- lua/core/utils/init.lua
This allows users to install null-ls sources automatically along with setting up sources similar to how `lspconfig` is configured with `mason-lspconfig`
> feat(plugins): add mason-null-ls plugin

- lua/core/utils/status.lua
Turns out listening to events is slower for chattier language servers than just checking every few ms.
> fix(status): disable lazy loading for LSP progress

- lua/core/utils/lsp.lua
- lua/user_example/init.lua
This adds a whitelist approach to `format_on_save` in addition to the existing blacklist.
Personally, I know which languages are "ok" to format on save, I do not know all the languages that are not
> feat(lsp): support format_on_save whitelist

- lua/default_theme/colors.lua
- lua/default_theme/plugins/nvim-web-devicons.lua
Currently packagejson icons look ugly due to dark red colour.
> feat(devicons): better highlights for devicon

- lua/core/mappings.lua
Lack of g in the word description
naviation→navigation
> chore:  fix typo in mappings.lua  desc

- lua/user_example/init.lua
Sorry @minhd-vu! I accidentally reverted this.
> chore(user_example): remove extra space in comment

- lua/default_theme/plugins/aerial.lua
This stops areial from erroring out three times on each cursor move, asking for AerialTypeIcon :-)
> chore(default_theme): Add missing Aerial icon

- lua/configs/lspkind.lua
`symbol` is already the default
> fix: unnecessary configuration option

- lua/configs/neo-tree.lua
the default `toggle_hidden` mapping was overrided by `prev_source`
> fix(neo-tree): add Mapping `h` to toggle_hidden

- lua/core/plugins.lua
Existing configuration, where `mason.nvim` `config` function requires `lspconfig` and `null-ls` before requiring `configs.mason`, creates a race condition due to plugin load order. `mason.nvim` add-on plugins - `mason-lspconfig.nvim` and `mason-null-ls.nvim` - start executing their installation hooks before `mason.nvim` configuration is loaded. During installation the `mason.nvim` configuration is loaded, therefore changing the settings and leading to errors like this (taken from `mason.log`):
```shell
[INFO  Tue Nov 29 11:59:24 2022] ...acker\start\mason.nvim/lua\mason-core\installer\init.lua:118: Executing installer for Package(name=lua-language-server)
[ERROR Tue Nov 29 11:59:25 2022] ...acker\start\mason.nvim/lua\mason-core\installer\init.lua:154: Installation failed for …
```
> fix(plugins): setting up mason before loading add-ons

- lua/configs/neo-tree.lua
When pressing `?` on neo-tree, the description for `O` mapping just says `<function>`. With this fix it shows `system_open`.
Before:
After:
> fix(neo-tree): fix system_open help description

- lua/core/mappings.lua
I capitalized Git in the mapping descriptions since it's a proper noun.
This is an insignificant change, but why not? ¯\\\_(ツ)_/¯
> Capitalize Git

- lua/plugins/neo-tree.lua
This will make it easier to copy file names and directories over to other applications, such as when you want to quickly locate a file in a system file explorer or cd into a directory in the terminal.
> feat: allow copying file name and absolute path in neo-tree

- lua/plugins/alpha.lua
I think adding the startup time to the default configuration might be a nice feature.
The code snippet is based on LazyVim and has been adapted by @luxus & @jay-babu and shared in the [AstroNvim discord](https://discord.com/channels/939594913560031363/1056415608968855572/1078643025472917516).
It looks like this:
> feat(alpha): added startup time to alpha

- lua/astronvim/utils/buffer.lua
Adds a function which allows navigating directly to a buffer by its position in the heirline buffer list (this differs from the buffer number itself!).
The modern equivalent of `BufferLineGoTo`.
Allows mappings like the following to be created:
```
["<leader>b1"] = { function() require("astronvim.utils.buffer").nav_to(1) end, desc = "Go to Buffer 1" }
```
or even (courtesy of @mehalter)
```
["<Tab>"] = { function() require("astronvim.utils.buffer").nav_to(vim.v.count) end, desc = "Go to Buffer" }
```
> feat(buffer): Add nav_to function

- lua/astronvim/utils/updater.lua
Fallback to "unknown" version if `astronvim_installation.version` is not provided and the `.git` directory is not available to allow `:checkhealth astronvim` to return.
Before:
```
astronvim: require("astronvim.health").check()
========================================================================
- ERROR: Failed to run healthcheck for "astronvim" plugin. Exception:
function health#check, line 20
Vim(eval):E5108: Error executing lua /home/maxime/.config/nvim/lua/astronvim/health.lua:6: attempt to concatenate a nil value
stack traceback:
/home/maxime/.config/nvim/lua/astronvim/health.lua:6: in function 'check'
[string "luaeval()"]:1: in main chunk
```
After:
```
astronvim: require("astronvim.health").check()
========================================================================
- INFO: …
```
> fix(updater): fallback to "unknown" version as last resort

- lua/astronvim/utils/status.lua
Fixes the delay in the macro_recording provider you can run `redrawstatus`.
> fix(status): add redraw execution to macro_recording

- lua/astronvim/utils/status.lua
I will preface this PR by saying I know very little lua and nothing about how the AstroNvim repo works.
Since the v3 update, when I exit nvim, I intermittently receive the below error. It seems to happen when I've been in a file for a longer period of time. If I open nvim in a file and close within 5s, the error never happens. I don't know the cause.
```
Error executing vim.schedule lua callback: /home/mark/.config/nvim/lua/astronvim/utils/status.lua:1065: Vim:E5108: Error executing lua /home/mark/.config/nvim
/lua/astronvim/utils/status.lua:555: bad argument #1 to 'rep' (string expected, got nil)
stack traceback:                                                                                                                                              
[C]: in function 'rep' …
```
> fix(utils): add nil check to sbar[i] calculation

- lua/astronvim/utils/lsp.lua
LSP semantic tokens are not perfect; bugs have been reported. Allow user to toggle semantic token highlights. Also very useful for theme/plugin development.
Neovim 0.9 introduces support for LSP semantic tokens. Users will experience the effect of LSP servers sending incorrect semantic tokens, resulting in incorrect syntax highlighting.
After lengthy discussions with @mehalter, we have seen that it is possible to handle these bugs accordingly, but agreed that we _should not_.
Instead, my suggestion is to provide the ability to disable/toggle semantic tokens as a whole, whether for a buffer, a language server, or globally.
AstroNvim already gives the user the ability to disable semantic tokens globally or per language server via the `lsp.on_attach` user option.
This change addresses …
> LSP - Toggle Semantic Token highlights

- lua/astronvim/bootstrap.lua
Looks like the new config directory detection did not take into account that the `vim.fn.stdpath` will return a path with backslashes on Windows. I added the backslash to the pattern.
> fix(bootstrap): "improved" config directory detection respects backslash

- lua/astronvim/utils/init.lua
Changes made in db9f4aa91cf33aefe66facfd46575fac491d3bc6 did not use the new property names.
> Use correct property names for nvim_get_hl

- lua/astronvim/utils/init.lua
> fix(utils): system_open in neotree on windows, use "cmd.exe /K explorer" instead of "explorer"

- lua/astronvim/autocmds.lua
- lua/astronvim/mappings.lua
- lua/plugins/core.lua
- lua/resession/extensions/astronvim.lua
This adds a new feature in a non-breaking way to use [`resession.nvim`](https://github.com/stevearc/resession.nvim/). We have made this toggle-able through `vim.g.resession_enabled = true` to enable the experimental feature. This comes with a lot more flexibility and allows us to use extensions to appropriately restore sessions with multiple tabs with our tab-scoped buffer management.
The goal is to remove `neovim-session-management` as the default session manager in AstroNvim v4 and just use `resession.nvim`. This does require lots of testing and the feature is experimental/probably buggy.
> Custom Session Management with Resession.nvim

- lua/astronvim/utils/buffer.lua
`<leader>c` with disabled bufdelete plugin leads to error messages:
```
E5108: Error executing lua: .../.config/nvim/lua/astronvim/utils/buffer.lua:72: attempt to concatenate local 'bufnr' (a nil value)                               
stack traceback:
.../.config/nvim/lua/astronvim/utils/buffer.lua:72: in function 'close'
.../.config/nvim/lua/astronvim/mappings.lua:49: in function <.../.config/nvim/lua/astronvim/mappings.lua:49>
```
This behavior is fixed by guarding the nil `bufnr` value.
> fix(buffer): fix close without bufdelete

- lua/plugins/git.lua
Bugs Fixed:
- Fixes `(UNKNOWN PLUGIN): Error executing lua: attempt to call a nil value` error message when writing a git commit message using AstroNvim. This was caused by `gitsigns` being loaded for `gitcommit` files, this PR disables that.
Other:
I don't think there is any use case where `gitsigns` is required for a `gitcommit` file, since the commit message is not in a file tracked by git. Please correct me if I'm wrong.
> fix(plugins): don't load git signs for gitcommit

- lua/plugins/neo-tree.lua
There was a missing key in the config for neo-tree causing empty folders to render the default char shown in the commit below.
https://github.com/nvim-neo-tree/neo-tree.nvim/pull/600/commits/465add19fc88e0257d06da7d5c3ca75c51449f0f#diff-b2cb9452bc9983e124579b119e5d1e01dbe8627f638852ef8ae2ec049c84b920
> Fix neo-tree empty folder icon with nerdfont v3

- lua/plugins/cmp.lua
fix cmp menu width when using Rust
see : https://github.com/hrsh7th/nvim-cmp/issues/1154
> fix cmp menu width when using Rust

- .github/README.md
The reason for this addition is because it took me a very long time to understand it to begin with.
To new users who never heard of Nerd Fonts, and who may not realize exactly how fonts work on a terminal emulator, they may not understand that you don't actually have to install the Nerd Font on a remote system. It took me a few hours of tinkering to realize this, so the annotation would help future users who end up in my shoes.
The reason for the [1] and [2] is to differentiate between the note related to terminal colors and the note related to nerd fonts. I put the nerd font one above the terminal color one because it appears first in the list.
> Added explanation for Nerd Fonts to readme

- lua/plugins/cmp.lua
`make` is usually available on UNIX systems, but the current check sets the `build` property if `win32` IS PRESENT.
This means that the `build` property is present in the case of Windows, and absent in the case of UNIX.
As a Windows user, I get an error every time I update my plugins, and UNIX users don't get the feature they usually can install correctly.
I updated the check to detect if `win32` is NOT `1`, instead of NOT `0`, so that the `build` property is only present on non-Windows systems.
> Only build LuaSnip if NOT on Windows

- lua/astronvim/autocmds.lua
- lua/astronvim/mappings.lua
- lua/astronvim/options.lua
- lua/astronvim/utils/git.lua
- lua/plugins/git.lua
Many users (myself included) like tracking their dotfiles in bare git repos which rely on setting a custom worktree to work. Unfortunately, this also means that while editing dotfiles, it's not possible to see git diffs in the gutter or open lazygit in the correct repository as without a `.git` folder it is difficult to know whether a file is being tracked by a bare repo or not.
This PR adds git integration when editing files within custom worktrees, allowing toggleterm and gitsigns gutter highlighting to work as you would expect them to. It also fixes the AstroGitFile event to trigger when a file within a custom worktree is opened, allowing plugins like gitsigns to propely lazy load. 
This functionality is opt-in, so those who don't rely on custom worktrees won't notice anything.
To …
> feat(options): add setting to enable git integration for custom worktrees

- lua/plugins/ui.lua
This fixes an issue where notifications were obscuring UI elements of plugins like [Noice](https://github.com/folke/noice.nvim/blob/main/lua/noice/config/views.lua
).
> fix(ui): notifications appearing on top in unintended situations

- lua/astronvim/utils/init.lua
In the `alpha_button` function, its return has an `opts` table that defines the position of the cursor. I changed it to the beginning of the button. Before it was in the middle of the text.
> fix(utils): set alpha cursor in a better position

- lua/astronvim/mappings.lua
This makes it so that the git root used for telescope commands is determined based on the file you are in when calling it. This prevents instances where the wrong git commits/branches are brought up. For example, if you have a project open, but you decide to open up a single file from another git repo (say your `.zshrc`), `require("telescope.builtin").git_commits()` will bring up the commit history for the original project, while `require("telescope.builtin").git_bcommits()` won't even work.
> fix(mappings): use git root of current file for git telescope mappings

- lua/astronvim/options.lua
Any lines starting with a `#` is unable to be indented with `smartindent`
Related issues:
- https://github.com/LunarVim/LunarVim/issues/3219
- https://github.com/LnL7/vim-nix/issues/16
I confirmed this problem also exist in AstroNvim.
- AstroNvim Version: v3.33.2
- Neovim Version: v0.9.1
- OK Using stable Neovim >= 0.8.0
- OK `git` is installed: Used for core functionality such as updater and plugin management
- OK `xdg-open` is installed: Used for `gx` mapping for opening files with system opener (Optional)
- WARNING `lazygit` is not installed: Used for mappings to pull up git TUI (Optional)
- OK `node` is installed: Used for mappings to pull up node REPL (Optional)
- OK `gdu` is installed: Used for mappings to pull up disk usage analyzer (Optional)
- WARNING `btm` is not installed: Used …
> fix(options): don't set `smartindent`

- lua/astronvim/utils/ui.lua
This PR adds a notification when toggling url highlighting to be consistent with the other url toggles.
> fix(ui): notify when toggling url highlighting

- lua/astronvim/utils/status/provider.lua
This PR does two things: 
1. It changes the default fallback to display noname buffers in heirline as "[No Name]"  instead of "Empty" (which imo doesn't really make sense once the buffer has been modified) to align with default vim naming.
2. It also fixes an issue where when a modifier (other than ":t") is applied to the `file_info` component, the fallback is not always shown, for example with the following custom component:
```lua
status.component.file_info {
filename = { modify = ":~:." },
},
```
The issue is that applying custom modifiers to `filename` for a `[No Name]` file sets it from an empty string to a nonempty string. This PR resolves this by performing the fallback check on the original path before it was modified.
Here's a screenshot showing the changes:
> fix(status): always show correct filename for files without a name

- lua/astronvim/mappings.lua
- lua/astronvim/utils/ui.lua
Currently, `toggle_syntax_highlighting` is rather janky. It completely breaks when `vim.g.ui_notifications_enabled=true` (prolly something to do with syntax highlighting within the notify buffer) and doesn't always work as expected between multiple buffers.
This PR does 3 things:
1. It fixes syntax highlighting when ui notifications are enabled
2. It fixes the inconsistent toggling behavior between buffers by enabling and disabling syntax locally instead of globally (TS highlighting was already buffer-local before, this just makes native syntax highlighting buffer-local as well)
3. It also disables/enables semantic token highlighting when appropriate
> fix(ui): improve toggle syntax highlighting

- lua/astronvim/utils/ui.lua
This *actually* fixes the duplicate messages when toggling semantic token highlighting.
> fix(ui): don't check every lsp client when toggling semantic tokens

- lua/astronvim/autocmds.lua
- lua/astronvim/mappings.lua
I was thinking about switching over to stow to manage my dotfiles when I encountered this issue where gitsigns wasn't loaded when opening the files from the symlink. It turns out that symlinks were not being resolved in the git directory check. This fixes that.
Edit: I also enabled the follow option in the telescope finder to fix this for the "Find AstroNvim config files" mapping.
> fix(autocmds): resolve git dir for symlinked files in `AstroGitFile` event

- lua/plugins/neo-tree.lua
Sets `<c-j>`/`<c-/k>` to navigate up/down neo-tree filter results to align with telescope and cmp bindings
> feat(neo-tree): add mappings to navigate neo-tree filter popup

- lua/astronvim/autocmds.lua
We probably shouldn't show this
> fix(autocmds): set cmdheight=0 in alpha

- lua/astronvim/utils/lsp.lua
I wanted the possibility to do a workspace symbol search without having to type the word as it is right now, but getting it from a word of the current buffer: Many well-known IDEs consider the word under the cursor or the selected text after pressing the "symbol search" shortcut.
I had multiple ways to achieve this:
- define the `default` parameter in the `vim.ui.input()` function, which would pre-fill the dialog with the word under the cursor. However, the main drawback is that if the user wants to do an unrelated workspace symbol search (unrelated to the word under the cursor), they would have to delete (by pressing backspace) the whole word before typing.
- Define a workspace symbol search in visual mode. This way, the user would have to select the word (or more than a word) …
> feat(lsp): symbol search for word under cursor

- lua/plugins/cmp.lua
Refs: 67c2c71
Closes #2225
Bugs Fixed:
- removed `<C-x>` mapping from luasnip, which is for decrementing numbers by default
> revert(luasnip): don't map `store_selection_keys` by default

- lua/astronvim/plugins/neo-tree.lua
Removes the "o" keymap as there is a conflict with Neotree's new default ["Order by" keymaps]
(https://github.com/nvim-neo-tree/neo-tree.nvim/commit/70ab62c8cc5d039766c039597c7c33a76d74fd11). Hopefully shouldn't be too much of a breaking change since there are several other existing keymaps that do the same thing.
> fix(neo-tree)!: conflict with new "Order by" keymaps

- lua/astronvim/autocmds.lua
This makes the `neo-tree` filesystem refresh when closing a lazygit terminal. AstroNvim is already doing this for the git status source, and it would be good to refresh the other sources as well. The buffer source, obviously, wouldn't need to be refreshed.
> fix(autocmds): refresh Neo-Tree filesystem when closing lazygit

- lua/plugins/heirline.lua
Adds tabline padding for undotree.
At first I thought it would be best to leave this in a personal config since undo tree is not included in AstroNvim, but unfortunately doing so is not that simple and results in the mental overhead of having to manually keep a user heirline config in sync with the core one. I thought it might be best to include it in core given the plugin's popularity (especially considering edgy and Nvim-tree are there as well).
**Before**
**After**
> chore(heirline): add tabline padding to undotree

- lua/plugins/treesitter.lua
bug: Autocompletion with slash bug with tsx. Typing something like `<div/`, will result in `<div/div>`, which is invalid JSX. This disables that functionality until it is fixed.
https://github.com/windwp/nvim-ts-autotag/issues/125
> fix(nvim-ts-autotag): TS closing tag disabled until issue is closed

- lua/plugins/heirline.lua
Adds tabline padding to overseer, doesn't interfere with `direction=bottom`
None
> chore(heirline): add tabline padding to overseer

- lua/astronvim/options.lua
This fixes what seems to be a typo where we accidentally try to concatenate a boolean with a string in options error message.
> fix(options): don't concatenate boolean in error message

- lua/plugins/cmp.lua
Bugs Fixed:
- Hitting tab can jump to previously completed snippet from anywhere in the same file
Other:
This PR changes the snippet jump action to only be executed when the cursor is inside the current snippet.
Previously, when e.g. trying to indent a black line using tab an incomplete jumped through previous snippet would result in an unexpected jump to that snippet.
Please let me know if this was a desired behaviour and the selection between local and global snippet jumps should be configurable instead.
> fix(cmp): only jump through snippet locally

- lua/astronvim/plugins/_astrocore_options.lua
Enable [confirm](https://neovim.io/doc/user/options.html#'confirm') by default so that certain operations that would normally fail because of unsaved changes to a buffer, e.g., ":q" and ":e", instead raise a dialog asking users if they wish to save the current file(s)
> feat(options): enable confirm by default

- lua/astronvim/plugins/telescope.lua
Fixes an issue where the telescope previewer does not use treesitter (e.g. when starting up nvim with an empty buffer).
N/A
> fix(telescope): load treesitter with telescope

- README.md
I believe the whitespace in and around the HTML for the badges as is causes these visual issues where link underlines are visible. This PR compacts the HTML to where that is no longer an issue - and the layout of the badges still appears the same.
> docs: improve badge layout

- lua/astronvim/plugins/cmp_luasnip.lua
This will update the internal usage of `vim.snippet` to match the new API for `vim.snippet.active` as proposed here:
- https://github.com/neovim/neovim/pull/28560
> fix(cmp): update `vim.snippet` to use updated `active` API

- README.md
it looks like with the release of 4.0, AstroUpdatePackages was removed and AstroUpdate does the same thing (it calls astrocore and updates everything)
> doc: update the update command

- lua/astronvim/plugins/_astrocore_options.lua
When ['shiftwidth'](https://neovim.io/doc/user/options.html#'shiftwidth') is zero, the ['tabstop'](https://neovim.io/doc/user/options.html#'tabstop') value will be used, so we can avoid one extra step when changing the number of spaces that a `<Tab>` in the file counts for
> refactor(options): set shiftwidth to automatically copy 'tabstop' value

- lua/astronvim/plugins/configs/guess-indent.lua
- lua/astronvim/plugins/guess-indent.lua
This updates the lazy loading of `guess-indent` to be a bit more efficient and improved. It requires the changes proposed here:
- https://github.com/NMAC427/guess-indent.nvim/pull/20
We have moved to my own fork where these changes are available until the PR is merged.
> perf(guess-indent): improve lazy loading

- README.md
Fixes the incorrect admonition syntax introduced in AstroNvim/AstroNvim@0f875f4a7f1963d6c61eb564cadb8e556e406dd5 :
> docs: fix incorrect admonition syntax

- lua/astronvim/lazy_snapshot.lua
- lua/astronvim/plugins/configs/guess-indent.lua
- lua/astronvim/plugins/guess-indent.lua
This reverts commit 3d094ea7a6dafa90ac7bf6f48ffb399b28c22b12.
Waiting on:
- https://github.com/NMAC427/guess-indent.nvim/pull/20
> perf(guess-indent): improve lazy loading of guess-indent

- lua/astronvim/plugins/telescope.lua
A follow-up of 016c2cfc5288118f315a7fb26082d90d86a529b6 by ensuring `.git` folders are properly excluded from Telescope search results on Windows machines.
The original Regex file patterns of `"^%.git/"` and `"/%.git/"` could not match Git folders on Windows because Windows uses backward slashes (`\`) instead of forward slashes. 
Steps to reproduce:
1. Install AstroNvim on a Windows machine
2. Clone this repo
3. Run `:Telescope find_files`
4. Search for the word `.git`
- Before: `.git\*` files will show up
- After: The Git files are hidden
| Before | After |
| ------ | ----- |
| ![image](https://github.com/user-attachments/assets/55f6b71f-9e60-4459-9d51-d89473652563) | ![image](https://github.com/user-attachments/assets/97dcdd34-2bec-4cd5-a6fc-2b1f490d8c0a)
> fix(telescope): ensure `.git` folders are always ignored on Windows

- lua/astronvim/plugins/_astrolsp.lua
Replace the incorrect reference of `module` with `operation` in the file operations event handler.
--
> fix(_astrolsp): use correct key when indexing file_operations table

- lua/astronvim/plugins/snacks.lua
Added the snacks undo history picker, which uses the same keybind as the teloscope plugin 
https://github.com/AstroNvim/astrocommunity/blob/main/lua/astrocommunity/editing-support/telescope-undo-nvim/init.lua
> feat(snacks): add undo history picker

- lua/astronvim/plugins/highlight-colors.lua
The `highlight-colors`'s config was trying to disable `enabled_named_colors`, but according to the plugin's docs it's spelled as `enable_named_colors` (without a final `d` in `enable`) which lead to the config being ignored. This PR fixes the name of the setting
> fix(highlight-colors): fix typo in config option

- lua/astronvim/plugins/snacks.lua
From the [Snacks notifier documentation](https://github.com/folke/snacks.nvim/blob/main/docs/notifier.md), it looks like the keys to the `icons` table should be lowercase. Changing them fixes an issue where the icons take up two spaces instead of one.
Before:
After:
> fix(snacks): Fix Snacks notifier icons

- lua/astronvim/plugins/blink.lua
Fix no snippet icon in blink.cmp when use `lspkind` symbols
- before
- after
> fix(blink): fix missing snippet icon when use `lspkind` symbols
