AstroNvim/AstroNvim

init.lua, lua/core/defaults.lua
One of my commits merged while pre-commit was in review has broken
this. Sorry!
=> Make `main` pre-commit clean again

lua/configs/lsp/lsp-installer.lua, lua/configs/lsp/server-settings/rust_analyzer.lua
Small patch to make maintenance simpler:-)
Then add rust_analyzer LSP configuration. It is pretty close to what the manual suggests AFAICT.
=> Rust analyzer

.pre-commit-config.yaml
Pre-commit.ci has trouble downloading stylua, so try building it
instead.
=> Fix pre-commit.ci

README.md
Document how some of the earlier commits can be used to extend AstroVim.
=> Document some extension options in README.md

lua/configs/bufferline.lua, lua/configs/indent-line.lua, lua/configs/lualine.lua, lua/onedark/others.lua
=> Added support for neo-tree

lua/onedark/others.lua
=> Added lightspeed highlight groups

lua/core/autocmds.lua
Do not medddle with dashboard settings without the dashboard!
=> Do not apply dashboard autocmd without dashboard

lua/configs/dashboard.lua
Will provide the correct count of loaded plugins when the using Neovim on Windows.
=> Checking the OS to correctly show how many pluing are loaded

README.md, lua/configs/lsp/lsp-installer.lua
Added the ability for user level LSP server settings and updated README with examples.
Fixes #109
=> Add user LSP server settings

README.md, lua/configs/lsp/handlers.lua
This is a test branch to help extend the overriding of the on_attach function.
Fixes #131
=> Added on_attach_override

lua/core/plugins.lua
Realized that I forgot to add packer's configuration to the user configuration options.
=> Added packer user configuration

lua/core/plugins.lua
=> Remove friendly-snippets lazy loading

lua/core/plugins.lua
there was a slight issue with telescope lazy loading. This fixes it.
=> fix telescope lazy loading for dressing and other plugins

lua/core/utils.lua
This adds some basic error checking when trying to load files in the `user/` folder. This basically checks if the file exists and if it does, will give an error if it is unable to `require` it. It uses `vim.notify` so if the file is loaded after plugins are initiated then a notification window pops up, but if it's before like loading the `user/init.lua` then it will just appear at the bottom of the window below the status line.
Example: https://asciinema.org/a/zchfnljtyXwKWYI5jjrrw8f4V
Resolves #232
=> Added basic error checking on user folder loading

lua/configs/lualine.lua, lua/core/plugins.lua, lua/default_theme/base.lua, lua/default_theme/colors.lua, lua/lualine/themes/default_theme.lua
This PR is going to make lualine play more nicely with other themes as well as make it significantly easier for the user to config from the ground up in `user/init.lua` instead of being forced into the default.
=> Make lualine follow theme colors

lua/configs/indent-o-matic.lua, lua/core/plugins.lua
https://github.com/Darazaki/indent-o-matic
this is a very simple and quite fast indent detection plugin
=> Add automatic indent detection

lua/core/ui.lua
Signed-off-by: Micah Halter <micah@balena.io>
=> Fix focusing on window pop up

lua/configs/which-key.lua
=> Add missing telescope which-key bindings

lua/core/mappings.lua
Signed-off-by: Micah Halter <micah@balena.io>
=> Fix updated session bindings

lua/configs/lsp/handlers.lua, lua/core/plugins.lua
=> fix bug in lsp handlers

README.md
=> Add optional requirements for default set up

lua/core/autocmds.lua
=> Augroup bug fix

lua/core/plugins.lua
=> Another stab at fixing packer rebasing

lua/core/plugins.lua
=> Add fzy plugin if user is on windoze

lua/core/mappings.lua
=> Add description to each mapping

lua/configs/which-key-register.lua
They are inverted in the wc menu
=> Fix inverted Save/Load Session menu in which-key

lua/core/ui.lua
Make code more understandable and easier to read after initial telescope stack overflow bug fix.
=> Clean up new telescope fix

lua/configs/Comment.lua, lua/core/plugins.lua
=> Rename comment to Comment

lua/configs/highlighturl.lua, lua/core/plugins.lua, lua/default_theme/others.lua
This is an initial test of adding url highlighting to AstroNvim
=> Added URL highlighting

lua/configs/lsp/lsp-installer.lua, lua/configs/nvim-lsp-installer.lua, lua/core/plugins.lua
This is an initial update to fix AstroNvim to work with the new nvim-lsp-installer API. I think we can do more to simplify what we currently have but we can at least get something that works out now.
=> Conform to the new lsp-installer API

lua/core/plugins.lua
=> Pin neo-tree for stability

lua/configs/aerial.lua, lua/configs/telescope.lua, lua/configs/which-key-register.lua, lua/core/mappings.lua
This enables the Telescope picker for Aerial and also fixes some typos in the mappings.
=> Improving Aerial

lua/configs/alpha.lua, lua/core/options.lua, lua/core/utils.lua, lua/user_example/init.lua
=> Generalize Alpha buttons

init.lua, lua/core/options.lua, lua/core/utils.lua
There's no need for us to have these in a separate function. We can just put them where we set all the options
Resolves #430
=> Move builtins to the more general options file

lua/configs/which-key-register.lua, lua/core/mappings.lua, lua/core/plugins.lua
=> Move from vim-bbye to bufdelete.nvim

lua/core/mappings.lua
This also fixes a bug I introduced on accident
=> Remove terminal binding autocmd

lua/configs/lsp/handlers.lua, lua/core/mappings.lua
=> Move lsp bindings to on_attach

lua/configs/autopairs.lua
=> Add API for adding rules to nvim-autopairs

lua/user_example/init.lua
Signed-off-by: Micah Halter <micah@balena.io>
=> fix null_ls autoformat with multiple files open

lua/configs/indent-line.lua, lua/configs/neo-tree.lua, lua/core/options.lua, lua/core/plugins.lua, lua/core/utils.lua
=> Move plugin setup to the correct location

lua/core/plugins.lua
Continuation of #514 to improve the base lazy loading
=> Lazy loading core plugins to save startup time

.github/CODE_OF_CONDUCT.md, .github/CONTRIBUTING.md, .github/PULL_REQUEST_TEMPLATE/chore.md, .github/PULL_REQUEST_TEMPLATE/feature.md, .github/PULL_REQUEST_TEMPLATE/fix.md
=> docs: add contribution guidelines

lua/core/plugins.lua
=> fix(comment): fix Comment.nvim lazy loading

lua/core/mappings.lua
=> fix(mappings): prompt when closing unsaved buffers

lua/core/plugins.lua
=> revert: move back to fzy-native for windows

lua/configs/cmp.lua
=> fix(cmp): don't select automatically on enter

lua/configs/neo-tree.lua
=> chore(neo-tree): close neovim if neotree is last window

lua/core/plugins.lua
=> chore(cmp): improve lazy loading of snippets and cmp

lua/configs/indent-line.lua
=> fix(indent_blankline): fix unaligned indent character

lua/configs/Comment.lua, lua/configs/aerial.lua, lua/configs/alpha.lua, lua/configs/autopairs.lua, lua/configs/better_escape.lua, lua/configs/bufferline.lua, lua/configs/cinnamon.lua, lua/configs/cmp.lua, lua/configs/colorizer.lua, lua/configs/feline.lua, lua/configs/gitsigns.lua, lua/configs/icons.lua, lua/configs/indent-line.lua, lua/configs/indent-o-matic.lua, lua/configs/luasnip.lua, lua/configs/neo-tree.lua, lua/configs/notify.lua, lua/configs/null-ls.lua, lua/configs/nvim-lsp-installer.lua, lua/configs/session_manager.lua, lua/configs/smart-splits.lua, lua/configs/telescope.lua, lua/configs/toggleterm.lua, lua/configs/treesitter.lua, lua/configs/which-key.lua, lua/core/options.lua, lua/core/plugins.lua
I don't think there is any need to wrap these configurations in functions
=> chore(core): simplify plugin configuration

.gitignore
=> chore: add gui client config file to gitignore

.github/README.md
=> chore(docs): add xclip to dependency list

lua/configs/lsp/handlers.lua, lua/core/mappings.lua, lua/core/utils/init.lua, lua/user_example/init.lua
=> feat(core): add new section for configuring keymaps

init.lua, lua/core/bootstrap.lua, lua/core/options.lua, lua/core/plugins.lua, lua/core/utils/init.lua
Packer compiled file is loaded late in the startup which messes up colorscheme settings.
=> fix: load packer compilation during bootstrap stage

lua/core/utils/init.lua
=> fix(core): improve error reporting on failed loaded user module

lua/user_example/init.lua
This addresses issues discussed at #781
Signed-off-by: Osamu Aoki <osamu@debian.org>
Resolves #781
=> mappings and which-key

lua/default_theme/treesitter.lua
=> feat: better syntax highlighting for rust

.github/workflows/docs.yml, .gitignore, config.ld, lua/core/autocmds.lua, lua/core/utils/git.lua, lua/core/utils/init.lua, lua/core/utils/updater.lua, lua/user_example/init.lua
This will include improving the `user_example` and adding comments to API functions in the `utils/`
Resolves #756
Resolves #826
=> chore: improve comments and documentation in code

lua/core/mappings.lua
=> fix(mappings): update Comment.nvim mappings to new API

lua/core/autocmds.lua
=> fix(autocmds): improve sidebar auto quitting autocmd

.github/README.md
=> chore: fix typo in readme

lua/default_theme/plugins/bufferline.lua
=> Fixed Bufferline "modified_icon" highlight on inactive tabs.

lua/configs/aerial.lua
=> [Aerial] - Removed deprecation warning

lua/core/autocmds.lua
fixes #975
If there is only one window, do nothing
Otherwise, if all of the visible windows are neo-tree and aerial, close the current tab (if there are other tabs) or exit vim.
=> fix: auto-quit autocmd behavior

lua/core/status.lua
=> fix(status): deduplicate null-ls sources in statusline

lua/user_example/init.lua
=> chore(user_example): comment out non-default behavior from user_example

lua/configs/aerial.lua
https://github.com/stevearc/aerial.nvim/blob/e0215f9dcf55e917f547ad2c688be6fe67a5926d/lua/aerial/config.lua#L13
=> fix(aerial): min_width is set inside `layout`

lua/user_example/init.lua
=> chore(user_example): change time_ms to timeout_ms

lua/core/utils/ui.lua
=> fix(ui): show changed status for toggling autoformatting and tabline

lua/core/mappings.lua
Hey @syotaro, I noticed in the previous PR I wasn't paying attention. You only changed the title. I need you to reword the actual commit message. Thanks!
=> Fix Typo in Mappings.lua

lua/core/plugins.lua
`nvim-web-devicons` are further developed in a new repo.
=> fix: changed plugin repo

lua/core/utils/init.lua
=> v2.5.4 Nightly

lua/default_theme/plugins/treesitter.lua
Float number color needs to be the same as of integer number.
=> fix(treesitter): correct float color

lua/configs/heirline.lua, lua/core/plugins.lua
=> v2.8.2 Nightly

lua/core/autocmds.lua, lua/core/plugins.lua, lua/core/utils/init.lua
- Don't schedule plugin loading, this can cause instability
- Fixes Packer lazy loading with `module` and `cmd` (implemented a bandaid fix, hopefully will be fixed soon upstream)
Resolves #1366 
Resolves #1402 
Resolves #1398
=> v2.8.3 Nightly

lua/core/utils/init.lua
=> v2.9.1 Nightly

lua/core/autocmds.lua
=> v2.11.2 Nightly

.github/README.md
Add a twitter link to the readme.
=> chore(readme): add twitter and mastodon link

lua/core/utils/lsp.lua
sumneko got renamed https://github.com/neovim/nvim-lspconfig/pull/2439
=> fix(lsp): lua lsp is now called lua_ls

lua/astronvim/utils/updater.lua
=> fix(updater): fix rollback on stable releases

lua/astronvim/utils/updater.lua
=> fix(updater): typo in updater.lua

lua/astronvim/lazy.lua
=> AstroNvim v3.2.1 Nightly

.github/FUNDING.yml, lua/astronvim/lazy.lua
=> AstroNvim v3.3.2 Nightly

lua/astronvim/options.lua
=> Astronvim v3.4.1

lua/astronvim/utils/mason.lua, lua/plugins/configs/mason.lua, lua/plugins/mason.lua
=> v3.5.4 Nightly

lua/astronvim/autocmds.lua, lua/astronvim/mappings.lua, lua/astronvim/utils/lsp.lua
=> 3.8.0 Nightly

lua/plugins/mason.lua
https://github.com/williamboman/mason.nvim#lazynvim
=> feat: adding build to mason.nvim

lua/astronvim/autocmds.lua, lua/astronvim/utils/init.lua
=> v3.12.0 Nightly

lua/astronvim/mappings.lua
add debug Evaluate Expression for debug.
=> feat(dap): add debug Evaluate Expression

lua/plugins/cmp.lua
This is probably behavior the user expects by default.
=> PageUp / PageDown support for auto completion

.github/README.md
Adding astrocommunity as the first feature to hopefully reduce the surprise of it's existence with new users
=> docs: Adding astrocommunity as a feature

lua/lazy_snapshot.lua, lua/plugins/core.lua
Relies on v2 release of [`nvim-window-picker`](https://github.com/s1n7ax/nvim-window-picker)
=> fix(plugins): update nvim-window-picker to v2

lua/astronvim/utils/lsp.lua
Fixes Issue #2020
Bugs Fixed:
- Wrong condition check for semantic tokens support before enabling them
=> fix(lsp): condition to check if lsp server supports semantic tokens

lua/plugins/treesitter.lua
=> v3.28.3 Nightly

lua/astronvim/autocmds.lua, lua/astronvim/utils/status/component.lua, lua/lazy_snapshot.lua
=> v3.29.2 Nightly

lua/plugins/neo-tree.lua
Add command `F` to neo-tree in order to `find_files` inside a specific directory. This feature is very helpfull when working in big projects.
=> feat(neo-tree): add `F` to find in dir neo tree

lua/astronvim/utils/status/component.lua
See https://github.com/rebelot/heirline.nvim/pull/133
=> chore(status): remove unecessary callback for `macro_recording`

lua/astronvim/autocmds.lua, lua/astronvim/mappings.lua, lua/astronvim/utils/status/provider.lua, lua/lazy_snapshot.lua, lua/plugins/neo-tree.lua
=> v3.34.1 Nightly

lua/astronvim/utils/updater.lua
Fix incorrect description in comment
None
=> chore(utils): fix updater descriptions

lua/astronvim/options.lua
Improves documentation for shortmess flags
None
=> chore(options): improve shortmess description

lua/astronvim/plugins/_astrocore_mappings.lua, lua/astronvim/plugins/_astrolsp.lua, lua/astronvim/plugins/_astrolsp_mappings.lua, lua/astronvim/plugins/alpha.lua, lua/astronvim/plugins/cmp.lua, lua/astronvim/plugins/core.lua, lua/astronvim/plugins/dap.lua, lua/astronvim/plugins/git.lua, lua/astronvim/plugins/heirline.lua, lua/astronvim/plugins/lsp.lua, lua/astronvim/plugins/mason.lua, lua/astronvim/plugins/mini-indentscope.lua, lua/astronvim/plugins/neo-tree.lua, lua/astronvim/plugins/telescope.lua, lua/astronvim/plugins/ui.lua
Depends on https://github.com/folke/lazy.nvim/pull/1058
=> perf(plugins): lazy now ignores plugin fragments if a plugin is disabled

.github/README.md
This fixes two dead links in the main README.md.
=> docs: fix two links in README.md

lua/lazy_snapshot.lua, lua/plugins/treesitter.lua
=> v3.38.2 Nightly

.github/README.md
aloupe — Yesterday at 4:53 PM
Hi, minor nitpick on the landing page/readme:
AstroNvim is an aesthetic and feature-rich neovim config(...)
That's not proper usage of "aesthetic", it should be "aesthetically pleasing", "aesthetically appealing", something like that. "Aesthetic" means "having to do with aesthetics" - its not a qualitative adjective like that It's a common mistake and might get normalized through usage eventually... just thought that sentence wasn't very aesthetically pleasing
https://discord.com/channels/939594913560031363/939857762043695165/1200468459377672242
=> docs(readme): better wording that is more aesthetically pleasing

lua/astronvim/health.lua, lua/astronvim/utils/init.lua
=> v3.43.0 Nightly

lua/plugins/configs/alpha.lua
show how many plugins has loaded vs total
=> update alpha config in footer

README.md
Adds admonition block for notes in README.md
=> docs: add admonition for notes

lua/astronvim/plugins/_astrocore_autocmds.lua
=> fix(_astrocore_autocmds): typo in terminal_settings description

lua/astronvim/init.lua
=> fix: astrocore spelling in require

lua/astronvim/plugins/_astrocore_autocmds.lua
=> fix(autocmd): typo in unlist qf description

lua/astronvim/plugins/configs/alpha.lua
Obey the user's request for no icons in Alpha.
:warning: This does change the icon from a plug 🔌  to a package 📦  as defined in AstroUi.
=> feat: Make Alpha Nerdfont Optional
